### ISSUE TITLE
Error Loading extension section v3_ca

### ISSUE THREAD

**Issue by jeliss** [rklomp/sophos-utm-letsencrypt#6] opened 2017-02-17 15:53 UTC
I'm getting the following on running ./getssl -f example.org.
Real domain replaced.

Any Ideas?  the csr file is empty.

```
firewall:/root/.getssl/example.org # ls -la
total 16
drwxr-xr-x 2 root root 4096 Feb 16 16:50 .
drwxr-xr-x 3 root root 4096 Feb 16 16:51 ..
-rw-r--r-- 1 root root 3046 Feb 16 16:08 getssl.cfg
-rw-r--r-- 1 root root    0 Feb 16 16:50 example.org.csr
-rw------- 1 root root 3243 Feb 16 16:17 example.org.key

```

```
firewall:/root # ./getssl -f example.org
creating domain csr - /root/.getssl/example.org/example.org.csr
Error Loading extension section v3_ca
1435629192:error:2206D06C:X509 V3 routines:X509V3_parse_list:invalid null name:v3_utl.c:326:
1435629192:error:22097069:X509 V3 routines:DO_EXT_NCONF:invalid extension string:v3_conf.c:139:name=subjectAltName,section=
1435629192:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:93:name=subjectAltName, value=
Registering account
Verify each domain
Verifying example.org
example.org is already validated
Verifying www.example.org
www.example.org is already validated
Verification completed, obtaining certificate.
Error Loading extension section v3_ca
1435629192:error:2206D06C:X509 V3 routines:X509V3_parse_list:invalid null name:v3_utl.c:326:
1435629192:error:22097069:X509 V3 routines:DO_EXT_NCONF:invalid extension string:v3_conf.c:139:name=subjectAltName,section=
1435629192:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:93:name=subjectAltName, value=
getssl: Sign failed:   "detail": "Error parsing certificate request. Extensions in the CSR marked critical can cause this error: https://github.com/letsencrypt/boulder/issue
```

**Comment by rklomp** [comment] 2017-02-17 15:55
Can you share your config? What is the value of your SANS parameter?

**Comment by jeliss** [comment] 2017-02-17 15:58
Sure.
This is the one in the firewall:/root/.getssl/example.org directory.
```
# Uncomment and modify any variables you need
# see https://github.com/srvrco/getssl/wiki/Config-variables for details
# see https://github.com/srvrco/getssl/wiki/Example-config-files for example configs
#
# The staging server is best for testing
#CA="https://acme-staging.api.letsencrypt.org"
# This server issues full certificates, however has rate limits
#CA="https://acme-v01.api.letsencrypt.org"

#PRIVATE_KEY_ALG="rsa"

# Additional domains - this could be multiple domains / subdomains in a comma separated list
# Note: this is Additional domains - so should not include the primary domain.
SANS="www.example.org"

# Acme Challenge Location. The first line for the domain, the following ones for each additional domain.
# If these start with ssh: then the next variable is assumed to be the hostname and the rest the location.
# An ssh key will be needed to provide you with access to the remote server.
# Optionally, you can specify a different userid for ssh/scp to use on the remote server before the @ sign.
# If left blank, the username on the local server will be used to authenticate against the remote server.
# If these start with ftp: then the next variables are ftpuserid:ftppassword:servername:ACL_location
# These should be of the form "/path/to/your/website/folder/.well-known/acme-challenge"
# where "/path/to/your/website/folder/" is the path, on your web server, to the web root for your domain.
#ACL=('/var/www/example.org/web/.well-known/acme-challenge'
#     'ssh:server5:/var/www/example.org/web/.well-known/acme-challenge'
#     'ssh:sshuserid@server5:/var/www/example.org/web/.well-known/acme-challenge'
#     'ftp:ftpuserid:ftppassword:example.org:/web/.well-known/acme-challenge')

ACL=('ssh:web@webserver:/var/www/example.org/www/.well-known/acme-challenge')

#Set USE_SINGLE_ACL="true" to use a single ACL for all checks
USE_SINGLE_ACL="true"
```

**Comment by rklomp** [comment] 2017-02-17 15:59
Duplicate of https://github.com/srvrco/getssl/issues/255

**Closed as completed by rklomp** 2017-02-17 15:59 UTC
